name: Kanbloom

services:
  frontend:
    build: ./frontend
    container_name: react-kanbloom
    ports:
      - "${VITE_PORT}:${VITE_PORT}"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: django-kanbloom
    command: /app/entrypoint.sh
    restart: unless-stopped
    ports:
      - "${DJANGO_PORT}:${DJANGO_PORT}"
    volumes:
      - ./backend:/app
      - ./media:/media
      - static:/static
    env_file:
      - .env

volumes:
  dist:
  static: